(function (global) {
  const LR = (global.LR = global.LR || {});

  LR.DEFAULT_EVENT = {
    name: 'TechSummit 2026',
    dates: 'Oct 14 – 16',
    city: 'Las Vegas',
  };

  LR.PRICING = {
    discountRate: 0.10,
    currentPackageId: 'pkg-pro',
    defaultRentalQty: { 'rental-iphone': 3, 'rental-ipad': 0 },
  };

  LR.DEFAULT_CATALOG = {
    packages: [
      {
        id: 'pkg-basic',
        type: 'package',
        name: 'Basic',
        price: 349,
        licenses: 2,
        features: ['Standard lead capture', 'CSV export', 'Email support'],
      },
      {
        id: 'pkg-pro',
        type: 'package',
        name: 'Pro',
        price: 699,
        licenses: 5,
        features: [
          'Custom qualifiers + dashboards',
          'CRM integration (SF, HubSpot)',
          'Priority support',
        ],
      },
      {
        id: 'pkg-enterprise',
        type: 'package',
        name: 'Enterprise',
        price: 1499,
        licenses: 20,
        features: [
          'AI lead enrichment',
          'Templates, surveys, email campaigns',
          'Dedicated CSM',
        ],
      },
    ],
    rentals: [
      {
        id: 'rental-iphone',
        type: 'rental',
        device: 'iphone',
        tag: 'Smartphone',
        name: 'iPhone Rental',
        price: 120,
        description:
          'iPhone 13 pre-installed with scanning software. Picked up at registration.',
      },
      {
        id: 'rental-ipad',
        type: 'rental',
        device: 'ipad',
        tag: 'Tablet',
        name: 'iPad Rental',
        price: 150,
        description:
          'iPad with scanning software. Ideal for larger booths and stationary check-in.',
      },
    ],
    addons: [
      {
        id: 'addon-ai-enrichment',
        type: 'addon',
        icon: '✨',
        name: 'AI Lead Enrichment - 100 records',
        description:
          'Auto-enrich up to 100 captured leads with firmographics, intent signals, recommended next action, and CRM-ready contact details.',
        category: 'Feature',
        price: 249,
        priceUnit: 'flat',
      },
      {
        id: 'addon-basic-ai',
        type: 'addon',
        icon: '✨',
        name: 'Basic AI Enrichment - 100 records',
        description:
          'Auto-enrich up to 100 captured leads with firmographic data (company size, industry, location, headcount).',
        category: 'Feature',
        price: 95,
        priceUnit: 'flat',
      },
      {
        id: 'addon-questionnaires',
        type: 'addon',
        icon: '📋',
        name: 'Custom Questionnaires',
        description:
          'Build your own lead qualifier flow with branching logic, required-field validation, and multi-language support. Built in our self-service form designer.',
        category: 'Feature',
        price: 99,
        priceUnit: 'flat',
      },
      {
        id: 'addon-email',
        type: 'addon',
        icon: '📧',
        name: 'Email campaign',
        description:
          'Send branded pre-show invitations or post-event follow-ups, auto-personalized for each lead and scheduled to your timeline.',
        category: 'Feature',
        price: 149,
        priceUnit: 'flat',
      },
      {
        id: 'addon-crm',
        type: 'addon',
        icon: '🔌',
        name: 'CRM Integration',
        description:
          'Auto-sync captured leads in real time to Salesforce, HubSpot, or any major CRM. Includes field mapping, dedup rules, and live status during the event.',
        category: 'Feature',
        price: 199,
        priceUnit: 'flat',
      },
      {
        id: 'addon-api',
        type: 'addon',
        icon: '🔧',
        name: 'API Developer Access',
        description:
          'Full read/write API access for custom integrations. Includes documentation, sandbox environment, and authentication keys for your engineering team.',
        category: 'Service',
        price: 450,
        priceUnit: 'flat',
      },
      {
        id: 'addon-profile-questions',
        type: 'addon',
        icon: '➕',
        name: 'Additional Profile Questions (5)',
        description:
          'Add 5 extra qualifier questions beyond the 5 included in your package. Useful for capturing budget, timeline, decision-maker role, and product interest.',
        category: 'Feature',
        price: 45,
        priceUnit: 'block',
      },
    ],
  };

  LR.DEFAULT_EXHIBITORS = [
    {
      id: 'ex-contoso',
      name: 'Contoso Inc.',
      booth: 'B-247',
      hall: 'West Hall',
      contact: 'Sarah Chen',
      role: 'VP Marketing',
      email: 'sarah.chen@contoso.com',
      phone: '+1 (415) 555-0102',
      website: 'contoso.com',
      industry: 'SaaS / Cloud Infrastructure',
      size: '500-1,000 employees',
      location: 'San Jose, CA',
      package: 'Pro',
      addons: 'iPhone rental ×3',
      total: '$879',
      status: 'paid',
    },
    {
      id: 'ex-acme',
      name: 'Acme Corp.',
      booth: 'B-312',
      hall: 'West Hall',
      contact: 'James Peterson',
      role: 'CMO',
      email: 'j.peterson@acme.com',
      phone: '+1 (212) 555-0143',
      website: 'acme.com',
      industry: 'Industrial Manufacturing',
      size: '1,000-5,000 employees',
      location: 'New York, NY',
      package: 'Enterprise',
      addons: 'AI enrichment, email campaign',
      total: '$1,897',
      status: 'pending',
    },
    {
      id: 'ex-initech',
      name: 'Initech',
      booth: 'C-104',
      hall: 'East Hall',
      contact: 'Mike Bolton',
      role: 'Sales',
      email: 'mike@initech.com',
      phone: '+1 (404) 555-0188',
      website: 'initech.com',
      industry: 'Software',
      size: '50-200 employees',
      location: 'Atlanta, GA',
      package: 'Basic',
      addons: '—',
      total: '$349',
      status: 'paid',
    },
    {
      id: 'ex-vandelay',
      name: 'Vandelay Industries',
      booth: 'A-501',
      hall: 'Main Hall',
      contact: 'Art Vandelay',
      role: 'Founder',
      email: 'art@vandelay.com',
      phone: '+1 (212) 555-0277',
      website: 'vandelay.com',
      industry: 'Import / Export',
      size: '200-500 employees',
      location: 'New York, NY',
      package: 'Enterprise',
      addons: 'AI enrichment, surveys, iPad ×2',
      total: '$1,748',
      status: 'paid',
    },
    {
      id: 'ex-soylent',
      name: 'Soylent Inc.',
      booth: 'B-088',
      hall: 'West Hall',
      contact: 'Pat Green',
      role: 'Director',
      email: 'green@soylent.com',
      phone: '+1 (415) 555-0319',
      website: 'soylent.com',
      industry: 'Consumer Products',
      size: '50-200 employees',
      location: 'San Francisco, CA',
      package: '—',
      addons: '—',
      total: '—',
      status: 'not-accepted',
    },
    {
      id: 'ex-globex',
      name: 'Globex Ltd.',
      booth: 'C-220',
      hall: 'East Hall',
      contact: 'Hank Scott',
      role: 'Operations',
      email: 'h.scott@globex.com',
      phone: '+1 (617) 555-0411',
      website: 'globex.com',
      industry: 'Technology Services',
      size: '500-1,000 employees',
      location: 'Boston, MA',
      package: '—',
      addons: '—',
      total: '—',
      status: 'not-accepted',
    },
    {
      id: 'ex-fabrikam',
      name: 'Fabrikam Industries',
      booth: 'D-410',
      hall: 'Main Hall',
      contact: 'Robert Carter',
      role: 'Director, Platform Eng.',
      email: 'r.carter@fabrikam.com',
      phone: '+1 (512) 555-0163',
      website: 'fabrikam.com',
      industry: 'Industrial / IoT',
      size: '1,000-5,000 employees',
      location: 'Austin, TX',
      package: 'Pro',
      addons: 'Questionnaires, email campaign',
      total: '$947',
      status: 'paid',
    },
    {
      id: 'ex-northwind',
      name: 'Northwind Traders',
      booth: 'D-415',
      hall: 'Main Hall',
      contact: 'Diana Voss',
      role: 'Marketing Manager',
      email: 'd.voss@northwind.com',
      phone: '+1 (303) 555-0227',
      website: 'northwind.com',
      industry: 'Logistics',
      size: '200-500 employees',
      location: 'Denver, CO',
      package: 'Basic',
      addons: 'iPhone rental ×2',
      total: '$589',
      status: 'paid',
    },
    {
      id: 'ex-litware',
      name: 'Litware Inc.',
      booth: 'D-420',
      hall: 'Main Hall',
      contact: 'Joanne Park',
      role: 'CEO',
      email: 'j.park@litware.com',
      phone: '+1 (305) 555-0344',
      website: 'litware.com',
      industry: 'Telecommunications',
      size: '50-200 employees',
      location: 'Miami, FL',
      package: 'Pro',
      addons: 'CRM integration',
      total: '$898',
      status: 'paid',
    },
    {
      id: 'ex-adatum',
      name: 'Adatum Corporation',
      booth: 'B-156',
      hall: 'West Hall',
      contact: '—',
      role: '—',
      email: 'info@adatum.com',
      phone: '—',
      website: 'adatum.com',
      industry: 'Financial Services',
      size: '500-1,000 employees',
      location: 'Chicago, IL',
      package: 'Basic',
      addons: '—',
      total: '$349',
      status: 'paid',
    },
    {
      id: 'ex-adventure',
      name: 'Adventure Works',
      booth: 'C-305',
      hall: 'East Hall',
      contact: 'Michael Reed',
      role: 'Founder',
      email: 'mike@adventureworks.com',
      phone: '+1 (602) 555-0488',
      website: 'adventureworks.com',
      industry: 'Sporting Goods',
      size: '50-200 employees',
      location: 'Phoenix, AZ',
      package: 'Pro',
      addons: 'iPad rental ×1',
      total: '$849',
      status: 'paid',
    },
    {
      id: 'ex-trey',
      name: 'Trey Research',
      booth: 'A-203',
      hall: 'Main Hall',
      contact: 'David Cohen',
      role: 'Procurement Lead',
      email: 'd.cohen@treyresearch.com',
      phone: '+1 (206) 555-0521',
      website: 'treyresearch.com',
      industry: 'Market Research',
      size: '200-500 employees',
      location: 'Seattle, WA',
      package: 'Pro',
      addons: '—',
      total: '$699',
      status: 'paid',
    },
    {
      id: 'ex-coho',
      name: 'Coho Vineyard',
      booth: 'B-340',
      hall: 'West Hall',
      contact: 'Linda Park',
      role: 'Director, Operations',
      email: 'l.park@cohovineyard.com',
      phone: '+1 (312) 555-0613',
      website: 'cohovineyard.com',
      industry: 'Food & Beverage',
      size: '50-200 employees',
      location: 'Chicago, IL',
      package: 'Basic',
      addons: '—',
      total: '$349',
      status: 'paid',
    },
    {
      id: 'ex-wingtip',
      name: 'Wingtip Solutions',
      booth: 'A-118',
      hall: 'Main Hall',
      contact: 'Sarah Hayes',
      role: 'VP, Procurement',
      email: 's.hayes@wingtip.com',
      phone: '+1 (617) 555-0729',
      website: 'wingtip.com',
      industry: 'Consulting',
      size: '500-1,000 employees',
      location: 'Boston, MA',
      package: 'Pro',
      addons: 'iPhone rental ×2',
      total: '$939',
      status: 'paid',
    },
    {
      id: 'ex-proseware',
      name: 'Proseware Inc.',
      booth: 'D-510',
      hall: 'East Hall',
      contact: 'Raj Patel',
      role: 'Senior Engineer',
      email: 'r.patel@proseware.com',
      phone: '+1 (404) 555-0835',
      website: 'proseware.com',
      industry: 'Enterprise Software',
      size: '1,000-5,000 employees',
      location: 'Atlanta, GA',
      package: 'Enterprise',
      addons: 'AI enrichment',
      total: '$1,499',
      status: 'paid',
    },
  ];
})(window);
